fix: Don't erase PR message if editor exits with a non-zero code (#204)
This has bit me a few times when flailing with vim. The file is saved successfully but Vim exits with a non-zero exit code and I've managed to lose big walls of text this way.

Going to test by causing vim to fail when creating this very PR.

It works!

```
Creating pull request for branch travis/mer-3040-av-cli-dont-erase-pr-message-if-editor-exits-non-zero:
  - pushing to origin/travis/mer-3040-av-cli-dont-erase-pr-message-if-editor-exits-non-zero
  - saved pull request description to /Users/travis/Aviator/av/.git/av/tmp/av-pr-travis-mer-3040-av-cli-dont-erase-pr-message-if-editor-exits-non-zero.md (it will be automatically re-used if you try again)
error: text editor failed: command "vi" failed: exit status 2
```